### PR TITLE
analyzer: fix false positive with multiple pos args

### LINKED ISSUE #25: Incorrect detection of strings with multiple %[1]
https://github.com/catenacyber/perfsprint/pull/16 fails to consider cases where the one arguments is referenced multiple times:

```golang
package main

import "fmt"

func main() {
         _ = fmt.Sprintf("You say %[1]s, I also say %[1]s", "hello")
}
```

Using the version before the PR mentioned above, there is no change as positional arguments weren't supported.
```
$ go install github.com/catenacyber/perfsprint@v0.4.0
$ perfsprint --fix ./...
```

Using a the latest version (i.e. after the PR was merged) it detects and gives an inccorrect suggested "fix":
```console
$ go install github.com/catenacyber/perfsprint@v0.7.0
$ perfsprint --fix ./...
test/main.go:6:7: fmt.Sprintf can be replaced with string concatenation
test/main.go:3:8: Fix imports
````

The fix is:
```
package main

import

func main() {
         _ = "You say %[1]s, I also say "+"hello"
}
```

Given this is not a simple concatenation I would expect this to just not be flagged by perfsprint.

### PR DESCRIPTION
**Pull request by catenacyber**
Meant to fix #25

### CODE REVIEW

File: analyzer/analyzer.go [hunk 1]
```diff
@@ -62,6 +62,9 @@ func isConcatable(verb string) bool {
 		(strings.HasSuffix(verb, "%s") && !strings.Contains(verb, "%[1]s")) ||
 			(strings.HasSuffix(verb, "%[1]s") && !strings.Contains(verb, "%s"))
 
+	if strings.Count(verb, "[1]s") > 1 {
```
Comment (percivalalb) [inline analyzer/analyzer.go:65]: Should this be `%[1]s`?

Comment (catenacyber) [reply analyzer/analyzer.go]: indeed, thanks for spotting it
